# Generated by Django 3.1.5 on 2021-01-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('proposal', models.CharField(blank=True, max_length=50)),
                ('pi', models.CharField(max_length=100)),
                ('pi_email', models.EmailField(max_length=254)),
                ('summary', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('program', models.ManyToManyField(to='partners.ProgramType')),
                ('region', models.ManyToManyField(to='partners.Region')),
                ('semesters', models.ManyToManyField(to='partners.Semester')),
            ],
        ),
    ]
