# Generated by Django 3.1.5 on 2021-01-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20210121_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('name',)},
        ),
    ]
