# Generated by Django 3.1.5 on 2021-01-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20210122_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='proposal',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
