# Generated by Django 3.1.5 on 2021-01-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_cohort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='semesters',
        ),
        migrations.AddField(
            model_name='partner',
            name='cohorts',
            field=models.ManyToManyField(to='partners.Cohort'),
        ),
        migrations.AddField(
            model_name='semester',
            name='cohort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='partners.cohort'),
            preserve_default=False,
        ),
    ]
