# Generated by Django 3.1.5 on 2021-03-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20210218_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='proposal',
            new_name='proposal_code',
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.TextField(verbose_name='people involved in coordiating the project')),
                ('institution', models.CharField(max_length=120, verbose_name='supporting institution or organization')),
                ('description', models.TextField(verbose_name='project description')),
                ('use', models.TextField(verbose_name='how will this project make use of LCO’s unique capabilities?')),
                ('experience', models.TextField(verbose_name='what experience do you have of running educational programs')),
                ('size', models.PositiveSmallIntegerField(choices=[(0, 'Small (<50)'), (1, 'Medium (50 - 200)'), (2, 'Large (200 - 1000)'), (3, 'Very large (> 1000)')])),
                ('support', models.TextField(verbose_name='how will you support your users?')),
                ('help', models.TextField(verbose_name='what help do you need from LCO in setting up your project?')),
                ('extension', models.TextField(verbose_name='is this an extension of an existing or previous project?')),
                ('time', models.IntegerField(verbose_name='hours requested')),
                ('time_reason', models.TextField(verbose_name='justification of time requested')),
                ('comments', models.TextField(verbose_name='any comments')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.cohort')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner')),
            ],
        ),
    ]
