# Generated by Django 3.1.5 on 2021-03-23 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0008_auto_20210322_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='proposal_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='comments',
            field=models.TextField(blank=True, verbose_name='any comments'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='people',
            field=models.TextField(verbose_name='people involved in coordinating the project'),
        ),
    ]
