# Generated by Django 3.1.5 on 2021-03-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20210323_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='active_call',
            field=models.BooleanField(default=False),
        ),
    ]
