# Generated by Django 3.1.5 on 2021-03-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_cohort_active_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='rejected',
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=0),
        ),
    ]
