# Generated by Django 3.1.5 on 2021-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_auto_20210324_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='cohorts',
            field=models.ManyToManyField(blank=True, to='partners.Cohort'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Accepted'), (3, 'Rejected')], default=0),
        ),
    ]
