# Generated by Django 3.1.5 on 2021-04-19 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_auto_20210415_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='call',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
