# Generated by Django 3.1.5 on 2021-05-17 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_auto_20210419_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='proposalfile',
            field=models.FileField(blank=True, upload_to='proposals'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.PositiveSmallIntegerField(choices=[(0, 'Accepted'), (1, 'Rejected'), (2, 'Further Questions')], default=0)),
                ('hours', models.FloatField(default=0.0, help_text='hours awarded')),
                ('emailed', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.proposal')),
            ],
        ),
    ]
