# Generated by Django 3.2.3 on 2021-05-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_auto_20210517_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='verdict',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rejected'), (1, 'Accepted'), (2, 'Further Questions')], default=0),
        ),
    ]
