# Generated by Django 3.2.3 on 2021-05-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_alter_review_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='emailed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
