# Generated by Django 3.2.3 on 2021-07-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0020_alter_review_emailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='active_report',
            field=models.BooleanField(default=False),
        ),
    ]
