# Generated by Django 3.2.18 on 2023-07-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0023_proposal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
