# Generated by Django 3.1.5 on 2021-02-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20210218_1535'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('partner', 'period')},
        ),
    ]
