# Generated by Django 3.1.5 on 2021-03-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210218_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprint',
            name='demographic',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Under-served or under-represented'), (1, 'Developing world'), (2, 'Well served communities'), (99, 'Other')], verbose_name='audience demographic'),
        ),
        migrations.AlterField(
            model_name='imprint',
            name='impact',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
