# Generated by Django 3.2.3 on 2021-06-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210322_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted')], default=0),
        ),
        migrations.AlterField(
            model_name='imprint',
            name='demo_other',
            field=models.TextField(blank=True, null=True, verbose_name='other demographic'),
        ),
    ]
