# Generated by Django 3.2.3 on 2021-08-17 13:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210622_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprint',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
    ]
